# Message: generates uart_config.inc from a simple pin configuration file.
if(NOT DEFINED INPUT_FILE)
  message(FATAL_ERROR "INPUT_FILE is not defined")
endif()

if(NOT EXISTS "${INPUT_FILE}")
  message(FATAL_ERROR "UART configuration file '${INPUT_FILE}' not found")
endif()

if(NOT DEFINED OUTPUT_FILE)
  message(FATAL_ERROR "OUTPUT_FILE is not defined")
endif()

if(NOT DEFINED CFG_TUD_CDC_VALUE)
  message(FATAL_ERROR "CFG_TUD_CDC_VALUE is not defined")
endif()

set(cfg_tud_cdc "${CFG_TUD_CDC_VALUE}")
if(NOT cfg_tud_cdc MATCHES "^[0-9]+$")
  message(FATAL_ERROR "CFG_TUD_CDC_VALUE '${cfg_tud_cdc}' is not a valid integer")
endif()

file(READ "${INPUT_FILE}" uart_config_raw)
string(REPLACE "\r\n" "\n" uart_config_raw "${uart_config_raw}")
string(REPLACE "\r" "\n" uart_config_raw "${uart_config_raw}")
string(REPLACE ";" "\\;" uart_config_raw "${uart_config_raw}")
string(REGEX REPLACE "\n+$" "" uart_config_raw "${uart_config_raw}")

if(uart_config_raw STREQUAL "")
  set(uart_config_lines "")
else()
  string(REPLACE "\n" ";" uart_config_lines "${uart_config_raw}")
endif()

set(entries "")
set(entry_count 0)
set(pio_sm 0)
set(uart0_used FALSE)
set(uart1_used FALSE)
set(used_pio_sms "")
set(used_pin_pairs "")

foreach(line IN LISTS uart_config_lines)
  string(STRIP "${line}" line)
  if(line STREQUAL "")
    continue()
  endif()
  if(line MATCHES "^#")
    continue()
  endif()

  math(EXPR entry_count "${entry_count} + 1")

  if(line MATCHES "TX=([0-9]+)")
    set(tx_pin "${CMAKE_MATCH_1}")
  else()
    message(FATAL_ERROR "Config line ${entry_count}: missing TX assignment ('${line}')")
  endif()

  if(line MATCHES "RX=([0-9]+)")
    set(rx_pin "${CMAKE_MATCH_1}")
  else()
    message(FATAL_ERROR "Config line ${entry_count}: missing RX assignment ('${line}')")
  endif()

  if(line MATCHES "LED=([0-9]+)")
    set(led_pin "${CMAKE_MATCH_1}")
  else()
    message(FATAL_ERROR "Config line ${entry_count}: missing LED assignment ('${line}')")
  endif()
  set(implicit_uart "")
  if(tx_pin STREQUAL "0" AND rx_pin STREQUAL "1")
    set(implicit_uart "0")
  elseif(tx_pin STREQUAL "4" AND rx_pin STREQUAL "5")
    set(implicit_uart "1")
  endif()
  list(APPEND used_pin_pairs "${tx_pin}:${rx_pin}")

  set(inst_value "0")
  set(sm_line "")
  set(explicit_uart "")
  set(explicit_pio "")
  if(line MATCHES "HW=([01])")
    set(explicit_uart "${CMAKE_MATCH_1}")
  endif()
  if(line MATCHES "UART=([01])")
    if(explicit_uart STREQUAL "" OR explicit_uart STREQUAL CMAKE_MATCH_1)
      set(explicit_uart "${CMAKE_MATCH_1}")
    else()
      message(FATAL_ERROR "Config line ${entry_count}: conflicting HW/UART assignments in '${line}'")
    endif()
  endif()
  if(line MATCHES "PIO=([0-9]+)")
    set(explicit_pio "${CMAKE_MATCH_1}")
  endif()

  if(NOT explicit_uart STREQUAL "" AND NOT explicit_pio STREQUAL "")
    message(FATAL_ERROR "Config line ${entry_count}: cannot specify both UART and PIO assignment ('${line}')")
  endif()

  if(NOT explicit_uart STREQUAL "")
    if(explicit_uart STREQUAL "0")
      if(uart0_used)
        message(FATAL_ERROR "Config line ${entry_count}: UART0 already assigned")
      endif()
      set(inst_value "uart0")
      set(uart0_used TRUE)
    elseif(explicit_uart STREQUAL "1")
      if(uart1_used)
        message(FATAL_ERROR "Config line ${entry_count}: UART1 already assigned")
      endif()
      set(inst_value "uart1")
      set(uart1_used TRUE)
    else()
      message(FATAL_ERROR "Config line ${entry_count}: unsupported UART index '${explicit_uart}'")
    endif()
  elseif(NOT explicit_pio STREQUAL "")
    list(FIND used_pio_sms "${explicit_pio}" _pio_index)
    if(NOT _pio_index EQUAL -1)
      message(FATAL_ERROR "Config line ${entry_count}: PIO state machine ${explicit_pio} already assigned")
    endif()
    if(explicit_pio GREATER 3)
      message(FATAL_ERROR "Config line ${entry_count}: PIO state machine ${explicit_pio} exceeds supported range (0-3)")
    endif()
    list(APPEND used_pio_sms "${explicit_pio}")
    set(inst_value "0")
    set(sm_line "        .sm = ${explicit_pio},\n")
  else()
    if(implicit_uart STREQUAL "0" AND uart0_used STREQUAL "FALSE")
      set(inst_value "uart0")
      set(uart0_used TRUE)
    elseif(implicit_uart STREQUAL "1" AND uart1_used STREQUAL "FALSE")
      set(inst_value "uart1")
      set(uart1_used TRUE)
    else()
      set(selected_sm "")
      while(selected_sm STREQUAL "")
        list(FIND used_pio_sms "${pio_sm}" _pio_index)
        if(_pio_index EQUAL -1)
          if(pio_sm GREATER 3)
            message(FATAL_ERROR "Config assigns more than 4 PIO UARTs; increase support if needed")
          endif()
          set(selected_sm "${pio_sm}")
          list(APPEND used_pio_sms "${selected_sm}")
        endif()
        math(EXPR pio_sm "${pio_sm} + 1")
      endwhile()
      set(inst_value "0")
      set(sm_line "        .sm = ${selected_sm},\n")
    endif()
  endif()

  set(entry "    {\n        .inst = ${inst_value},\n        .tx_pin = ${tx_pin},\n        .rx_pin = ${rx_pin},\n")
  if(NOT sm_line STREQUAL "")
    string(APPEND entry "${sm_line}")
  endif()
  string(APPEND entry "        .led_act_pin = ${led_pin}\n    },")
  list(APPEND entries "${entry}")
endforeach()

set(default_templates
  "UART0\\;0\\;1\\;2"
  "UART1\\;4\\;5\\;3"
  "PIO0\\;8\\;9\\;6"
  "PIO1\\;12\\;13\\;7"
  "PIO2\\;16\\;17\\;10"
  "PIO3\\;20\\;21\\;11"
)

foreach(template IN LISTS default_templates)
  if(entry_count GREATER_EQUAL cfg_tud_cdc)
    break()
  endif()
  if(NOT template MATCHES "^([^;]+);([^;]+);([^;]+);([^;]+)$")
    message(FATAL_ERROR "Internal error: invalid template '${template}'")
  endif()
  set(kind "${CMAKE_MATCH_1}")
  set(def_tx "${CMAKE_MATCH_2}")
  set(def_rx "${CMAKE_MATCH_3}")
  set(def_led "${CMAKE_MATCH_4}")
  set(pair_key "${def_tx}:${def_rx}")
  list(FIND used_pin_pairs "${pair_key}" _pair_index)
  if(NOT _pair_index EQUAL -1)
    continue()
  endif()

  set(def_inst "0")
  set(def_sm_line "")

  if(kind STREQUAL "UART0")
    if(uart0_used)
      continue()
    endif()
    set(def_inst "uart0")
  elseif(kind STREQUAL "UART1")
    if(uart1_used)
      continue()
    endif()
    set(def_inst "uart1")
  elseif(kind MATCHES "^PIO([0-3])$")
    set(def_sm "${CMAKE_MATCH_1}")
    set(target_sm "${def_sm}")
    list(FIND used_pio_sms "${target_sm}" _pio_index)
    if(NOT _pio_index EQUAL -1)
      set(target_sm "")
      foreach(candidate 0 1 2 3)
        list(FIND used_pio_sms "${candidate}" _cand_index)
        if(_cand_index EQUAL -1)
          set(target_sm "${candidate}")
          break()
        endif()
      endforeach()
      if(target_sm STREQUAL "")
        continue()
      endif()
    endif()
    set(def_inst "0")
    set(def_sm "${target_sm}")
    set(def_sm_line "        .sm = ${def_sm},\n")
  else()
    continue()
  endif()

  if(kind STREQUAL "UART0")
    set(uart0_used TRUE)
  elseif(kind STREQUAL "UART1")
    set(uart1_used TRUE)
  else()
    list(APPEND used_pio_sms "${def_sm}")
  endif()

  math(EXPR entry_count "${entry_count} + 1")
  list(APPEND used_pin_pairs "${pair_key}")

  set(entry "    {\n        .inst = ${def_inst},\n        .tx_pin = ${def_tx},\n        .rx_pin = ${def_rx},\n")
  if(NOT def_sm_line STREQUAL "")
    string(APPEND entry "${def_sm_line}")
  endif()
  string(APPEND entry "        .led_act_pin = ${def_led}\n    },")
  list(APPEND entries "${entry}")

  set(auto_msg "UART channel ${entry_count}: TX=${def_tx} RX=${def_rx} LED=${def_led}")
  if(kind STREQUAL "UART0")
    message(STATUS "${auto_msg} -> uart0 (auto)")
  elseif(kind STREQUAL "UART1")
    message(STATUS "${auto_msg} -> uart1 (auto)")
  else()
    message(STATUS "${auto_msg} -> PIO SM ${def_sm} (auto)")
  endif()
endforeach()

if(NOT entry_count EQUAL cfg_tud_cdc)
  message(FATAL_ERROR "UART config defines ${entry_count} channel(s) but CFG_TUD_CDC expects ${cfg_tud_cdc}")
endif()

get_filename_component(output_dir "${OUTPUT_FILE}" DIRECTORY)
if(NOT EXISTS "${output_dir}")
  file(MAKE_DIRECTORY "${output_dir}")
endif()

string(JOIN "\n" entries_blob ${entries})

set(file_header "/* Auto-generated from ${INPUT_FILE}. Do not edit directly. */\n")
set(file_body "${entries_blob}\n")
file(WRITE "${OUTPUT_FILE}" "${file_header}${file_body}")
