# Message: generates uart_config.inc from a simple pin configuration file.
if(NOT DEFINED INPUT_FILE)
  message(FATAL_ERROR "INPUT_FILE is not defined")
endif()

if(NOT EXISTS "${INPUT_FILE}")
  message(FATAL_ERROR "UART configuration file '${INPUT_FILE}' not found")
endif()

if(NOT DEFINED OUTPUT_FILE)
  message(FATAL_ERROR "OUTPUT_FILE is not defined")
endif()

if(NOT DEFINED CFG_TUD_CDC_VALUE)
  message(FATAL_ERROR "CFG_TUD_CDC_VALUE is not defined")
endif()

set(cfg_tud_cdc "${CFG_TUD_CDC_VALUE}")
if(NOT cfg_tud_cdc MATCHES "^[0-9]+$")
  message(FATAL_ERROR "CFG_TUD_CDC_VALUE '${cfg_tud_cdc}' is not a valid integer")
endif()

file(READ "${INPUT_FILE}" uart_config_raw)
string(REPLACE "\r\n" "\n" uart_config_raw "${uart_config_raw}")
string(REPLACE "\r" "\n" uart_config_raw "${uart_config_raw}")
string(REPLACE ";" "\\;" uart_config_raw "${uart_config_raw}")
string(REGEX REPLACE "\n+$" "" uart_config_raw "${uart_config_raw}")

if(uart_config_raw STREQUAL "")
  set(uart_config_lines "")
else()
  string(REPLACE "\n" ";" uart_config_lines "${uart_config_raw}")
endif()

set(entries "")
set(entry_count 0)
set(pio_sm 0)
set(uart0_used FALSE)
set(uart1_used FALSE)
set(used_pio_sms "")

foreach(line IN LISTS uart_config_lines)
  string(STRIP "${line}" line)
  if(line STREQUAL "")
    continue()
  endif()
  if(line MATCHES "^#")
    continue()
  endif()

  math(EXPR entry_count "${entry_count} + 1")

  if(line MATCHES "TX=([0-9]+)")
    set(tx_pin "${CMAKE_MATCH_1}")
  else()
    message(FATAL_ERROR "Config line ${entry_count}: missing TX assignment ('${line}')")
  endif()

  if(line MATCHES "RX=([0-9]+)")
    set(rx_pin "${CMAKE_MATCH_1}")
  else()
    message(FATAL_ERROR "Config line ${entry_count}: missing RX assignment ('${line}')")
  endif()

  if(line MATCHES "LED=([0-9]+)")
    set(led_pin "${CMAKE_MATCH_1}")
  else()
    message(FATAL_ERROR "Config line ${entry_count}: missing LED assignment ('${line}')")
  endif()

  set(inst_value "0")
  set(sm_line "")
  set(explicit_uart "")
  set(explicit_pio "")
  if(line MATCHES "HW=([01])")
    set(explicit_uart "${CMAKE_MATCH_1}")
  endif()
  if(line MATCHES "UART=([01])")
    if(explicit_uart STREQUAL "" OR explicit_uart STREQUAL CMAKE_MATCH_1)
      set(explicit_uart "${CMAKE_MATCH_1}")
    else()
      message(FATAL_ERROR "Config line ${entry_count}: conflicting HW/UART assignments in '${line}'")
    endif()
  endif()
  if(line MATCHES "PIO=([0-9]+)")
    set(explicit_pio "${CMAKE_MATCH_1}")
  endif()

  if(NOT explicit_uart STREQUAL "" AND NOT explicit_pio STREQUAL "")
    message(FATAL_ERROR "Config line ${entry_count}: cannot specify both UART and PIO assignment ('${line}')")
  endif()

  if(NOT explicit_uart STREQUAL "")
    if(explicit_uart STREQUAL "0")
      if(uart0_used)
        message(FATAL_ERROR "Config line ${entry_count}: UART0 already assigned")
      endif()
      set(inst_value "uart0")
      set(uart0_used TRUE)
    elseif(explicit_uart STREQUAL "1")
      if(uart1_used)
        message(FATAL_ERROR "Config line ${entry_count}: UART1 already assigned")
      endif()
      set(inst_value "uart1")
      set(uart1_used TRUE)
    else()
      message(FATAL_ERROR "Config line ${entry_count}: unsupported UART index '${explicit_uart}'")
    endif()
  elseif(NOT explicit_pio STREQUAL "")
    list(FIND used_pio_sms "${explicit_pio}" _pio_index)
    if(NOT _pio_index EQUAL -1)
      message(FATAL_ERROR "Config line ${entry_count}: PIO state machine ${explicit_pio} already assigned")
    endif()
    if(explicit_pio GREATER 3)
      message(FATAL_ERROR "Config line ${entry_count}: PIO state machine ${explicit_pio} exceeds supported range (0-3)")
    endif()
    list(APPEND used_pio_sms "${explicit_pio}")
    set(inst_value "0")
    set(sm_line "        .sm = ${explicit_pio},\n")
  else()
    if(uart0_used STREQUAL "FALSE")
      set(inst_value "uart0")
      set(uart0_used TRUE)
    elseif(uart1_used STREQUAL "FALSE")
      set(inst_value "uart1")
      set(uart1_used TRUE)
    else()
      set(selected_sm "")
      while(selected_sm STREQUAL "")
        list(FIND used_pio_sms "${pio_sm}" _pio_index)
        if(_pio_index EQUAL -1)
          if(pio_sm GREATER 3)
            message(FATAL_ERROR "Config assigns more than 4 PIO UARTs; increase support if needed")
          endif()
          set(selected_sm "${pio_sm}")
          list(APPEND used_pio_sms "${selected_sm}")
        endif()
        math(EXPR pio_sm "${pio_sm} + 1")
      endwhile()
      set(inst_value "0")
      set(sm_line "        .sm = ${selected_sm},\n")
    endif()
  endif()

  set(entry "    {\n        .inst = ${inst_value},\n        .tx_pin = ${tx_pin},\n        .rx_pin = ${rx_pin},\n")
  if(NOT sm_line STREQUAL "")
    string(APPEND entry "${sm_line}")
  endif()
  string(APPEND entry "        .led_act_pin = ${led_pin}\n    },")
  list(APPEND entries "${entry}")
endforeach()

if(NOT entry_count EQUAL cfg_tud_cdc)
  message(FATAL_ERROR "UART config defines ${entry_count} channel(s) but CFG_TUD_CDC expects ${cfg_tud_cdc}")
endif()

get_filename_component(output_dir "${OUTPUT_FILE}" DIRECTORY)
if(NOT EXISTS "${output_dir}")
  file(MAKE_DIRECTORY "${output_dir}")
endif()

string(JOIN "\n" entries_blob ${entries})

set(file_header "/* Auto-generated from ${INPUT_FILE}. Do not edit directly. */\n")
set(file_body "${entries_blob}\n")
file(WRITE "${OUTPUT_FILE}" "${file_header}${file_body}")
