# Common helper for parsing i2c_config.txt
function(parse_i2c_config INPUT_FILE)
  if(NOT EXISTS "${INPUT_FILE}")
    message(FATAL_ERROR "I2C configuration file '${INPUT_FILE}' not found")
  endif()

  file(READ "${INPUT_FILE}" I2C_CFG_RAW)
  string(REPLACE "\r\n" "\n" I2C_CFG_RAW "${I2C_CFG_RAW}")
  string(REPLACE "\r" "\n" I2C_CFG_RAW "${I2C_CFG_RAW}")
  string(REPLACE ";" "\\;" I2C_CFG_RAW "${I2C_CFG_RAW}")

  if(I2C_CFG_RAW STREQUAL "")
    set(I2C_CFG_LINES "")
  else()
    string(REPLACE "\n" ";" I2C_CFG_LINES "${I2C_CFG_RAW}")
  endif()

  set(_cfg_line "")
  foreach(line IN LISTS I2C_CFG_LINES)
    string(STRIP "${line}" line)
    if(line STREQUAL "")
      continue()
    endif()
    if(line MATCHES "^#")
      continue()
    endif()
    if(NOT _cfg_line STREQUAL "")
      message(FATAL_ERROR "I2C configuration may only contain one active line; found multiple entries")
    endif()
    set(_cfg_line "${line}")
  endforeach()

  set(_enabled 0)
  set(_sda -1)
  set(_scl -1)
  set(_led -1)
  set(_instance 0)
  set(_instance_name "i2c0")

  if(_cfg_line STREQUAL "")
    # Leave defaults: bridge disabled
    set(I2C_CFG_SOURCE_LINE "" PARENT_SCOPE)
  else()
    if(_cfg_line MATCHES "(^|[ \t])ENABLED=([01])")
      set(_enabled "${CMAKE_MATCH_2}")
    else()
      message(FATAL_ERROR "I2C configuration must specify ENABLED=0 or 1 ('${_cfg_line}')")
    endif()

    if(_enabled)
      if(_cfg_line MATCHES "(^|[ \t])SDA=([0-9]+)")
        set(_sda "${CMAKE_MATCH_2}")
      else()
        message(FATAL_ERROR "I2C configuration missing SDA pin ('${_cfg_line}')")
      endif()

      if(_cfg_line MATCHES "(^|[ \t])SCL=([0-9]+)")
        set(_scl "${CMAKE_MATCH_2}")
      else()
        message(FATAL_ERROR "I2C configuration missing SCL pin ('${_cfg_line}')")
      endif()

      if(_cfg_line MATCHES "(^|[ \t])LED=([0-9]+)")
        set(_led "${CMAKE_MATCH_2}")
      else()
        set(_led 14)
      endif()

      math(EXPR _sda_val "${_sda}")
      math(EXPR _scl_val "${_scl}")
      math(EXPR _led_val "${_led}")

      if(NOT (_sda_val GREATER_EQUAL 0 AND _sda_val LESS 30))
        message(FATAL_ERROR "I2C SDA pin '${_sda}' is out of range 0-29")
      endif()
      if(NOT (_scl_val GREATER_EQUAL 0 AND _scl_val LESS 30))
        message(FATAL_ERROR "I2C SCL pin '${_scl}' is out of range 0-29")
      endif()
      if(NOT (_led_val GREATER_EQUAL 0 AND _led_val LESS 30))
        message(FATAL_ERROR "I2C LED pin '${_led}' is out of range 0-29")
      endif()

      math(EXPR _is_even "${_sda_val} % 2")
      if(NOT _is_even EQUAL 0)
        message(FATAL_ERROR "I2C SDA pin '${_sda}' must be even")
      endif()

      math(EXPR _expected_scl "${_sda_val} + 1")
      if(NOT _expected_scl EQUAL _scl_val)
        message(FATAL_ERROR "I2C SCL pin '${_scl}' must be SDA+1 (found SDA=${_sda}, SCL=${_scl})")
      endif()

      math(EXPR _scl_is_odd "${_scl_val} % 2")
      if(NOT _scl_is_odd EQUAL 1)
        message(FATAL_ERROR "I2C SCL pin '${_scl}' must be odd")
      endif()

      math(EXPR _mod4 "${_sda_val} % 4")
      if(_mod4 EQUAL 0)
        set(_instance 0)
      elseif(_mod4 EQUAL 2)
        set(_instance 1)
      else()
        message(FATAL_ERROR "Unable to determine I2C instance for SDA=${_sda}")
      endif()
      set(_instance_name "i2c${_instance}")
    else()
      # Disabled: keep sentinel values
      math(EXPR _led_val "${_led}")
    endif()

    set(I2C_CFG_SOURCE_LINE "${_cfg_line}" PARENT_SCOPE)
  endif()

  set(I2C_CFG_ENABLED "${_enabled}" PARENT_SCOPE)
  set(I2C_CFG_SDA "${_sda}" PARENT_SCOPE)
  set(I2C_CFG_SCL "${_scl}" PARENT_SCOPE)
  set(I2C_CFG_LED "${_led}" PARENT_SCOPE)
  set(I2C_CFG_INSTANCE "${_instance}" PARENT_SCOPE)
  set(I2C_CFG_INSTANCE_NAME "${_instance_name}" PARENT_SCOPE)
endfunction()
